// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: wallet-service/proto/wallet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 4. Debit Wallet (For Checkout)
type DebitWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitWalletRequest) Reset() {
	*x = DebitWalletRequest{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitWalletRequest) ProtoMessage() {}

func (x *DebitWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitWalletRequest.ProtoReflect.Descriptor instead.
func (*DebitWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *DebitWalletRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DebitWalletRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DebitWalletRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type DebitWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitWalletResponse) Reset() {
	*x = DebitWalletResponse{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitWalletResponse) ProtoMessage() {}

func (x *DebitWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitWalletResponse.ProtoReflect.Descriptor instead.
func (*DebitWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *DebitWalletResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DebitWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DebitWalletResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// 1. Get Wallet
type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *Wallet) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Wallet) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Wallet) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionUid string                 `protobuf:"bytes,1,opt,name=transaction_uid,json=transactionUid,proto3" json:"transaction_uid,omitempty"`
	Amount         float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`     // "credit" or "debit"
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "Pending", "Completed", "Failed"
	Date           string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *Transaction) GetTransactionUid() string {
	if x != nil {
		return x.TransactionUid
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *GetWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

func (x *GetWalletResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// 2. Create Transaction (Add Funds / Razorpay Order)
type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTransactionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateTransactionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RazorpayOrderId string                 `protobuf:"bytes,3,opt,name=razorpay_order_id,json=razorpayOrderId,proto3" json:"razorpay_order_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Key             string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	TransactionId   string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name            string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Email           string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTransactionResponse) GetRazorpayOrderId() string {
	if x != nil {
		return x.RazorpayOrderId
	}
	return ""
}

func (x *CreateTransactionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTransactionResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateTransactionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTransactionResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 3. Confirm Payment
type ConfirmPaymentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId     string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	RazorpayPaymentId string                 `protobuf:"bytes,3,opt,name=razorpay_payment_id,json=razorpayPaymentId,proto3" json:"razorpay_payment_id,omitempty"`
	RazorpayOrderId   string                 `protobuf:"bytes,4,opt,name=razorpay_order_id,json=razorpayOrderId,proto3" json:"razorpay_order_id,omitempty"`
	RazorpaySignature string                 `protobuf:"bytes,5,opt,name=razorpay_signature,json=razorpaySignature,proto3" json:"razorpay_signature,omitempty"`
	Error             string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmPaymentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmPaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetRazorpayPaymentId() string {
	if x != nil {
		return x.RazorpayPaymentId
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetRazorpayOrderId() string {
	if x != nil {
		return x.RazorpayOrderId
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetRazorpaySignature() string {
	if x != nil {
		return x.RazorpaySignature
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfirmPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentResponse) Reset() {
	*x = ConfirmPaymentResponse{}
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResponse) ProtoMessage() {}

func (x *ConfirmPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResponse) Descriptor() ([]byte, []int) {
	return file_wallet_service_proto_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfirmPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfirmPaymentResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

var File_wallet_service_proto_wallet_proto protoreflect.FileDescriptor

const file_wallet_service_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"!wallet-service/proto/wallet.proto\x12\x06wallet\"`\n" +
	"\x12DebitWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"n\n" +
	"\x13DebitWalletResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"+\n" +
	"\x10GetWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"K\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\"\xb0\x01\n" +
	"\vTransaction\x12'\n" +
	"\x0ftransaction_uid\x18\x01 \x01(\tR\x0etransactionUid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"t\n" +
	"\x11GetWalletResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet\x127\n" +
	"\ftransactions\x18\x02 \x03(\v2\x13.wallet.TransactionR\ftransactions\"K\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\x90\x02\n" +
	"\x19CreateTransactionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11razorpay_order_id\x18\x03 \x01(\tR\x0frazorpayOrderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\"\xf8\x01\n" +
	"\x15ConfirmPaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12.\n" +
	"\x13razorpay_payment_id\x18\x03 \x01(\tR\x11razorpayPaymentId\x12*\n" +
	"\x11razorpay_order_id\x18\x04 \x01(\tR\x0frazorpayOrderId\x12-\n" +
	"\x12razorpay_signature\x18\x05 \x01(\tR\x11razorpaySignature\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"m\n" +
	"\x16ConfirmPaymentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fredirect_url\x18\x03 \x01(\tR\vredirectUrl2\xc4\x02\n" +
	"\rWalletService\x12@\n" +
	"\tGetWallet\x12\x18.wallet.GetWalletRequest\x1a\x19.wallet.GetWalletResponse\x12X\n" +
	"\x11CreateTransaction\x12 .wallet.CreateTransactionRequest\x1a!.wallet.CreateTransactionResponse\x12O\n" +
	"\x0eConfirmPayment\x12\x1d.wallet.ConfirmPaymentRequest\x1a\x1e.wallet.ConfirmPaymentResponse\x12F\n" +
	"\vDebitWallet\x12\x1a.wallet.DebitWalletRequest\x1a\x1b.wallet.DebitWalletResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_wallet_service_proto_wallet_proto_rawDescOnce sync.Once
	file_wallet_service_proto_wallet_proto_rawDescData []byte
)

func file_wallet_service_proto_wallet_proto_rawDescGZIP() []byte {
	file_wallet_service_proto_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_service_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_service_proto_wallet_proto_rawDesc), len(file_wallet_service_proto_wallet_proto_rawDesc)))
	})
	return file_wallet_service_proto_wallet_proto_rawDescData
}

var file_wallet_service_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wallet_service_proto_wallet_proto_goTypes = []any{
	(*DebitWalletRequest)(nil),        // 0: wallet.DebitWalletRequest
	(*DebitWalletResponse)(nil),       // 1: wallet.DebitWalletResponse
	(*GetWalletRequest)(nil),          // 2: wallet.GetWalletRequest
	(*Wallet)(nil),                    // 3: wallet.Wallet
	(*Transaction)(nil),               // 4: wallet.Transaction
	(*GetWalletResponse)(nil),         // 5: wallet.GetWalletResponse
	(*CreateTransactionRequest)(nil),  // 6: wallet.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 7: wallet.CreateTransactionResponse
	(*ConfirmPaymentRequest)(nil),     // 8: wallet.ConfirmPaymentRequest
	(*ConfirmPaymentResponse)(nil),    // 9: wallet.ConfirmPaymentResponse
}
var file_wallet_service_proto_wallet_proto_depIdxs = []int32{
	3, // 0: wallet.GetWalletResponse.wallet:type_name -> wallet.Wallet
	4, // 1: wallet.GetWalletResponse.transactions:type_name -> wallet.Transaction
	2, // 2: wallet.WalletService.GetWallet:input_type -> wallet.GetWalletRequest
	6, // 3: wallet.WalletService.CreateTransaction:input_type -> wallet.CreateTransactionRequest
	8, // 4: wallet.WalletService.ConfirmPayment:input_type -> wallet.ConfirmPaymentRequest
	0, // 5: wallet.WalletService.DebitWallet:input_type -> wallet.DebitWalletRequest
	5, // 6: wallet.WalletService.GetWallet:output_type -> wallet.GetWalletResponse
	7, // 7: wallet.WalletService.CreateTransaction:output_type -> wallet.CreateTransactionResponse
	9, // 8: wallet.WalletService.ConfirmPayment:output_type -> wallet.ConfirmPaymentResponse
	1, // 9: wallet.WalletService.DebitWallet:output_type -> wallet.DebitWalletResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wallet_service_proto_wallet_proto_init() }
func file_wallet_service_proto_wallet_proto_init() {
	if File_wallet_service_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_service_proto_wallet_proto_rawDesc), len(file_wallet_service_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_service_proto_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_service_proto_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_service_proto_wallet_proto_msgTypes,
	}.Build()
	File_wallet_service_proto_wallet_proto = out.File
	file_wallet_service_proto_wallet_proto_goTypes = nil
	file_wallet_service_proto_wallet_proto_depIdxs = nil
}
